"""Add tags and approved_by to content

Revision ID: 62cc1c9e6eb9
Revises: ac89eaf2d2c6
Create Date: 2025-11-02 13:31:40.290998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62cc1c9e6eb9'
down_revision = 'ac89eaf2d2c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
